---
modules-search: [ local ]

instances:
  - id: partition
    module: partition
    config: zog-partition.conf
  - id: mount
    module: mount
  - id: unpackfs
    module: unpackfs
    config: zog-unpackfs.conf
  - id: machineid
    module: machineid
  - id: fstab
    module: fstab
    config: zog-fstab.conf
  - id: locale
    module: locale
    config: zog-locale.conf
  - id: keyboard
    module: keyboard
    config: zog-keyboard.conf
  - id: hwclock
    module: hwclock
  - id: services
    module: services
    config: zog-services.conf
  - id: users
    module: users
    config: zog-users.conf
  - id: displaymanager
    module: displaymanager
    config: zog-displaymanager.conf
  - id: networkcfg
    module: networkcfg
  - id: shellprocess
    module: shellprocess
    config: zog-shellprocess.conf
  - id: packages
    module: packages
    config: zog-packages.conf
  - id: bootloader
    module: bootloader
    config: zog-bootloader.conf
  - id: umount
    module: umount

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - hwclock
      - services
      - packages
      - displaymanager
      - bootloader
      - users
      - networkcfg
      - shellprocess
      - umount
  - show:
      - finished

branding: zog

oem-setup: false
prompt-install: true
dont-show-operating-system-blacklist: false
