[General]
Session=plasmawayland
Session=plasmaX11
Font=Inter,11,-1,5,50,0,0,0,0,0
SessionButton=true
PowerButton=true
RebootButton=true
SuspendButton=true
HibernateButton=false
PartialBlur=true
ScreenPadding=0
