title   Zog Linux LTS
linux   /vmlinuz-linux-lts
initrd  /intel-ucode.img
initrd  /initramfs-linux-lts.img
options quiet rw intel_pstate=passive zram.enabled=1 root=UUID=__GENERATED_UUID__ rootflags=subvol=@
